version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=stack
      - POSTGRES_USER=stack
      - POSTGRES_PASSWORD=stackoverflow
    ports:
      - "5432:5432"
  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend/
    ports:
      - "8000:8000"
    depends_on:
      - db
